name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, windows-2019, macOS-10.15]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      # Used to host cibuildwheel
      - uses: actions/setup-python@v2

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.11.2
        env:
          CIBW_BUILD: cp36-* cp37-* cp38-* cp39-* cp310-* cp311-*
          CIBW_SKIP: "*-musllinux_*"
          CIBW_BEFORE_BUILD: pip install -r requirements.txt
          # https://cibuildwheel.readthedocs.io/en/stable/options/#examples_9
          # CIBW_BEFORE_BUILD_LINUX: apt update -y -q && apt install -y -q "libxml2=2.9.10*" "libxml2-dev=2.9.10*" libxslt1.1 libxslt1-dev
          CIBW_BEFORE_ALL_LINUX: yum install libxml2 libxml2-devel libxslt libxslt-devel -y
          CIBW_BEFORE_ALL_MACOS: brew install automake libtool && ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
          STATICBUILD: true
          # CIBW_CONFIG_SETTINGS: "--static-deps"
          # For macos env, see .github/workflows/wheels.yml
          LIBXML2_VERSION: 2.9.14
          LIBXSLT_VERSION: 1.1.35
          MACOSX_DEPLOYMENT_TARGET: 10.15

      - uses: actions/upload-artifact@v2
        with:
          path: ./wheelhouse/*.whl
          
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./wheelhouse/*.whl
